# Generated by Django 3.0.8 on 2020-07-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
    ]
