# Generated by Django 3.0.8 on 2020-07-18 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200718_2003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
    ]
